### ISSUE TITLE
Recommend using `ViewPager` instead of view for tab `Friends`, `Community`

### ISSUE THREAD

**Issue by thuypt** [cuongmanhvo162/Nimbl3Assignment#15]
Reload when change view mode isn't friendly to end users.

**Comment by cuongmanhvo162** [comment]
Hello, thanks for this suggestion. I was think about the ViewPager with Fragment, with these component, the app could cache data whenever user switching between the tabs. 

But the problem is, actually the data will not be reload when switching between ViewPager because data was stored in fragment. So, it actually have no different hence that data was just stored in more complicated way. Also, we will have to manage the fragment life circle.

With the current implementation, to prevent reload when switching between two tabs, I can just stored the list of each filter in its presenter.

**Comment by thuypt** [comment]
With current implementation, your solution is OK

**Comment by cuongmanhvo162** [comment]
Hello there, based on the idea I suggested, now the list of travel book categorized by Friends and Community will not be reloaded when switching tabs. Using the memory for now. Thanks.
